export default {
  ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1NDM0NDIwNjYsImlzcyI6Imh0dHBzOi8vYXBpLmVkbW9kby5jb20iLCJ1c2VyIjp7ImlkIjoxNDQ1MTU3NTJ9LCJhcHAiOnsiaWQiOjk4OX0sImV4cGlyZXNfaW4iOjg2NDAwLCJzY29wZXMiOiJhbGwifQ.3tfCVMKPVhTA9eecW9g3mhqk2jqVSki-OFHanGAOod3KdfeKpPULArT336fWbU-q7Pdd-k9T2HEIjEpUH1cwew",
  NAV_SUBMISSIONS: 'nav_submissions',
  FETCH_SUCCESS: 'submission_fetch_success',
  FETCH_FAILURE: 'submission_fetch_fail',
}
